### ISSUE TITLE
Basic support for stylus

### ISSUE THREAD

**Issue by simon-eome** [hippogamesunity/PixelStudioHub#8]
As an owner of a Galaxy Tab S3 with a stylus, the only thing I'm really missing is the support for two features:
1. Remove a pixel when the stylus button is pressed (or switch between pen and eraser)
2. Ignore touch when a stylus is detected

I know that there aren't many devices out there with a real stylus, but if these features are easy to integrate, they would be of huge benefit!

P.S.: It's an amazing tool, the best for it's purpose I've seen for Android so far! Great job!

**Comment by hippogamesunity** [comment]
I will check it, thanks!

**Comment by Bearroneous** [comment]
Hi! I would also like to promote the chance to have a bit of s-pen support. Having palm-detection would allow me to draw with the stylus while letting my finger move the canvas without accidentally drawing.

I find the s-pen's button a bit silly due to Samsung forcefully tying it to their own apps in some ways, but hey if you could find a way to utilize it to that'd be great! Having it switch the current tool to eraser (or last tool used, making it organically semi-customizable) would be awesome.

**Comment by hippogamesunity** [comment]
@Bearroneous I'm not an artist and I've never used a stylus) Maybe you could recommend me some cheap device with stylus support? Or maybe I can order active pen on aliexpress for that purpose? I mean I need a hardware for testing.

**Comment by Bearroneous** [comment]
Thanks for the reply. Unfortunatley samsung's s-pen is different from third-party styluses, so an active bluetooth stylus wouldnt quite be the same (I think?). I'm not a programmer in any way so I dont really know how to go about it. Perhaps theres an API or something you can use/refer to, to get the stylus' inputs? But if you don't have access to either some model of samsung note that supports s-pen, or another kind of stylus that uses a digitizer in the device, to test with, I am not sure what can be done.

A few other art apps like cloverpaint, medibang paint, etc have s-pen support, so I am hoping it's not too niche. Good luck however, I really do hope you look into it!

**Comment by hippogamesunity** [comment]
As I see, palm rejection simply disables touches when s-pen is used.
https://www.reddit.com/r/GalaxyNote8/comments/75oiya/s_pen_and_finger/

**Comment by hippogamesunity** [comment]
@Bearroneous I've just made a small test app https://yadi.sk/d/EtxtSoCUUZPJVg
Can you make 3 screenshots using it? Thanks!
- with a finger
- with a palm
- with a stylus

**Comment by hippogamesunity** [comment]
Oh, here is it from the market: https://play.google.com/store/apps/details?id=com.UnityInputTest

**Comment by Bearroneous** [comment]
@hippogamesunity 
Alright, I have done these on both the Galaxy Tab S3, and then on the Note3. Hopefully you can figure something useful from them!

With finger, I was just touching centre of the screen.
Tab:
![screenshot_20190218-221358_unity input test_tabfinger](https://user-images.githubusercontent.com/47713617/52950996-ca340180-33d4-11e9-9e96-ee3778b10290.jpg)

Note3:
![screenshot_2019-02-18-22-21-56_note3finger](https://user-images.githubusercontent.com/47713617/52951026-d4ee9680-33d4-11e9-9ce6-15c442afcd2e.png)

For Palm, I laid my hand across the screen (was tricky to press home+power for the screenshot at the same time)
Tab:
![screenshot_20190218-221936_unity input test_tabpalm](https://user-images.githubusercontent.com/47713617/52951096-f94a7300-33d4-11e9-933d-345a3baeeedd.jpg)

Note3:
![screenshot_2019-02-18-22-22-11_note3palm](https://user-images.githubusercontent.com/47713617/52951112-02d3db00-33d5-11e9-83f1-c8b0b9c0814f.png)

Stylus was jsut pressing it in the centre while screenshotting
Tab:
![screenshot_20190218-221434_unity input test_tabstylus](https://user-images.githubusercontent.com/47713617/52951134-12ebba80-33d5-11e9-8970-b2a19739de82.jpg)

Note3:
![screenshot_2019-02-18-22-22-42_note3stylus](https://user-images.githubusercontent.com/47713617/52951146-197a3200-33d5-11e9-9469-dabe39228940.png)

I hope that helps, if I didnt do it quite how you meant I can try again. As a side note there is a bit of innate palm detection in the samsung devices, where if I bring the stylus close to the screen it will ignore touches, but with pixel studio, its not so much palm detection that I was after, but to have the option in pixel studio to not draw with finger touches. This would allow me to pan the canvas around with a finger without drawing pixels, and only draw exclusively with the stylus. Sorry if I didn't explain that properly earlier. The innate palm detection did work in your testing program. There is a visualisation for the stylus when its hovering, but since it was touching in the test its not there.

If there is anything else I can do to help please let me know. Thanks heaps!

**Comment by hippogamesunity** [comment]
@Bearroneous many thanks! It seems than S-Pen is not recognized as a touch. So I think I only need to add  'Palm Rejection' to Settings that will simply ignore all touches on the canvas. Looks easy. Will update the app soon!

**Comment by Bearroneous** [comment]
That would be amazing! Thanks

**Comment by hippogamesunity** [comment]
Hi! I've just published 1.08 on Android. can you confirm it's cool now?)

**Comment by Bearroneous** [comment]
It was always cool, you just made it cooler! The new settings seem to work great, and you added a bunch of other stuff as well in the update. Thanks a lot!

**Comment by simon-eome** [comment]
That's awesome! Working with a stylus is very smooth now. Thanks a lot for adding the feature!

P.S.: Approved on Galaxy Tab S4
